--- drivers/misc/Makefile
+++ drivers/misc/Makefile
@@ -54,3 +54,4 @@
 obj-$(CONFIG_LATTICE_ECP3_CONFIG)	+= lattice-ecp3-config.o
 obj-$(CONFIG_SRAM)		+= sram.o
 obj-$(CONFIG_BCM2708_VCHIQ)	+= vc04_services/
+obj-$(CONFIG_VS10XX)		+= vs10xx/
